version: "3"
services:
  ultrahook:
    build:
      context: .
      dockerfile: ultrahook.Dockerfile
    environment:
      - "API_KEY=LD2DqAdj7YbFwEwYpalnUPpnv043hli5"
      - "DEST=http://localhost:8080"
    ports:
      - "5000:5000"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  server:
    depends_on:
      - ultrahook
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      - "HOSTNAME=0.0.0.0"
      - "PORT=8080"
      - "DATABASE_HOSTNAME=mongo"
      - "DATABASE_PORT=27017"
      - "DISCORD_CLIENT_ID=817871699730890802"
      - "DISCORD_CLIENT_SECRET=593RcNO_Qqk-hpyKBeuvVbEvi_vMu0Rb"
      - "GITHUB_CLIENT_ID=9e4c0a9f9c64edd6ca65"
      - "GITHUB_CLIENT_SECRET=d71c72ec620667412938582f18ff22f5918e6fca"
      - "GOOGLE_CLIENT_ID=331406027335-qlp9tgmmb6uu2egbea6a5pv91jp54tdi.apps.googleusercontent.com"
      - "GOOGLE_CLIENT_SECRET=ZPb9bmMFgM5omm-IGVZYVwDO"
      - "MICROSOFT_CLIENT_ID=84ebbe53-62dd-48a4-a2da-f5696a7773ce"
      - "MICROSOFT_CLIENT_SECRET=DCGzTfE9_vs125zLmpQAn79A_~LQv6w~Ko"
      - "TWITTER_CONSUMER_KEY=BsAFtxyYLQyXAFcbklJg6x6iD"
      - "TWITTER_CONSUMER_SECRET=XfX4wW3UdZAJ1E4WXQLlfShZtYXozJZKhcUkSi7LcdJXL3qIkQ"
      - "AES_SECRET=secret"
      - "AUTHORIZE_SECRET=secret"
    ports:
      - "8080:8080"
  client_mobile:
    depends_on:
      - server
    build:
      context: .
      dockerfile: mobile.Dockerfile
    environment:
      - "CLIENT_APK_PATH=/usr/share/app/client.apk"
    volumes:
      - client_volume:/usr/share/app
  client_web:
    depends_on:
      - server
      - client_mobile
    build:
      context: .
      dockerfile: web.Dockerfile
    environment:
      - "HOSTNAME=0.0.0.0"
      - "PORT=8081"
      - "CLIENT_APK_PATH=/usr/share/app/client.apk"
    ports:
      - "8081:8081"
    volumes:
      - client_volume:/usr/share/app
volumes:
  client_volume:
