name: Mobile Pull Request

on: pull_request

jobs:

  docker:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          docker build . -f mobile.Dockerfile
