name: Server Pull Request

on:
  pull_request:
    paths:
      - "server/**"

jobs:

  docker:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          docker build . -f server.Dockerfile
